name: Infra CI/CD

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Ensure S3 bucket exists for Terraform state
        run: |
          aws s3api head-bucket --bucket maracanaunews-terraform-state || aws s3api create-bucket --bucket maracanaunews-terraform-state --region us-east-1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build all Lambdas
        run: |
          cd packages/lambda && pnpm build && cd -
          cd packages/worker && pnpm build && cd -
          cd packages/scheduler && pnpm build && cd -

      - name: Zip all Lambdas
        run: |
          mkdir -p lambdas
          cd packages/lambda && zip -r ../../lambdas/lambda.zip . -x "node_modules/*" "__tests__/*" "tests/*" && cd -
          cd packages/worker && zip -r ../../lambdas/worker.zip . -x "node_modules/*" "__tests__/*" "tests/*" && cd -
          cd packages/scheduler && zip -r ../../lambdas/scheduler.zip . -x "node_modules/*" "__tests__/*" "tests/*" && cd -

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve
