name: Lambdas CI/CD

on:
  push:
    paths:
      - 'packages/lambda/**'
      - 'packages/worker/**'
      - 'packages/scheduler/**'
      - '.github/workflows/lambda.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Zip All Lambdas
        uses: ./.github/actions/build-zip-lambdas

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply (Deploy Lambda)
        working-directory: infra
        run: terraform apply -auto-approve
