name: Secret Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TruffleHog OSS Secret Scan
        uses: trufflesecurity/trufflehog@v3
        with:
          scanArguments: --only-verified
