name: Secret Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TruffleHog
        run: pip install trufflehog
      - name: TruffleHog OSS Secret Scan
        run: trufflehog filesystem .
